### ISSUE TITLE
[1.21.1-Neo] Crash on server boot.

### ISSUE THREAD

**Issue by Gbergz** [Cozary/Floral-Enchantment#1]
Crash on server boot.

MC: 1.21.1
NeoForge: 21.1.61
Floral Enchantment: 1.0.1

Crash report: https://gist.githubusercontent.com/Gbergz/1ea033a1df59717b391012c806b4ea6d/raw/27e0eac0406dfaf947d85a4a753c2e79e3094290/gistfile1.txt

```
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Floral Enchantment (floralench) has failed to load correctly
          java.lang.IllegalArgumentException: class com.cozary.floralench.EventHandler has no @SubscribeEvent methods, but register was called anyway.
          The event bus only recognizes listener methods that have the @SubscribeEvent annotation.
```

**Comment by Cozary** [comment]
My bad, it's easy to fix. I'll try to do the fix as soon as possible.

**Comment by Cozary** [comment]
It should be fixed with the new version.
